### ISSUE TITLE
TS imports error.

### ISSUE THREAD

**Issue by JamalLyons** [sindresorhus/alpha-sort#10]
Hello, im trying to use Alpha-sort for my TS project.

But I'm getting an error: 

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\thatguyjamal\Desktop\WorkSpace\Temrinal-ts\shell\node_modules\alpha-sort\index.js
require() of ES modules is not supported.
```
Now sure why I'm getting this when I imported it correctly. 

The code I'm using AS on is [here](https://sourceb.in/X7vyFA0muy). **Line 2, 47**

**Comment by sindresorhus** [comment]
Please read the release notes.
