### ISSUE TITLE
Ignore common words (articles)

### ISSUE THREAD

**Issue by binyamin** [sindresorhus/alpha-sort#8]
The words "the", "a", and "an"  don't usually make a difference in terms of order. (See [wikipedia](https://en.wikipedia.org/wiki/Alphabetical_order#The_and_other_common_words))

**Comment by binyamin** [comment]
@sindresorhus I can take this issue if you're okay with adding the feature.

**Comment by papb** [comment]
@b3u Can you give explicit examples of how the feature will be used and example outputs?

For example, it is not clear to me if you wish to ignore them only from the beginning of the string or in any place. And if you are only considering words separated by space (or which other separators); and if your feature will allow passing custom words to be ignored as well. And so on.

**Comment by binyamin** [comment]
@papb sure.
I only envision these words being ignored at the beginning of the string and when they are separated by a space. I didn't think about passing custom words. I think it's okay without it.
```js
let arr = ["the animal", "boys", "chair"];
return arr.sort(alphaSort);
```
This array should not be changed. Currently, "the animal" will go to the end of the array.

**Comment by papb** [comment]
What about `[" the animal", "boys", " chair", "  Something Else"]`?

And by `arr.sort(alphaSort)` you mean something like `arr.sort(alphaSort.ascendingIgnoringEnglishArticles)`?

**Comment by binyamin** [comment]
> What about `[" the animal", "boys", " chair", " Something Else"]`?

Are you referring to the uppercase letter "S"? I don't think it matters.
> And by arr.sort(alphaSort) you mean something like arr.sort(alphaSort.ascendingIgnoringEnglishArticles)?

Unless it should be the default behavior. I think it's common practice to ignore articles when sorting alphabetically.

**Comment by papb** [comment]
@b3u I was mainly referring to the leading spaces, but used the opportunity to ask about uppercase as well.

Hmm, I don't think this being default is reasonable:

* Not everyone uses english
* There are lots of use cases for sorting things lexicographically which are not immediately connected to language

**Comment by binyamin** [comment]
Gotcha. Spaces should not make a difference, as they're not part of the alphabet. I see your argument regarding it not being the default behavior.

**Comment by binyamin** [comment]
@papb I really appreciate your attention to detail here. Since you began by asking for more information, I felt as if the issue was poorly written. When you preface issue responses with "thanks for this issue", you can stop others from feeling this way. (Totally not your fault; it happens _all the time_ on GitHub)

**Comment by papb** [comment]
@b3u Thanks for the heads up :grinning: sorry about that. I am not the owner of the repository so I thought saying 'thanks for the issue' would not be appropriate. I was just trying to predict what kind of extra information @sindresorhus might want, so you could get ahead of that :)

**Comment by sindresorhus** [comment]
> Since you began by asking for more information, I felt as if the issue was poorly written.

Asking for more information is a common thing. I don't think you should assume ill-intent. Even if you write the best issue in the whole world, you might be missing some info that we need that you could not have foreseen. Generally, just assume people commenting have the best intention.

> When you preface issue responses with "thanks for this issue", you can stop others from feeling this way.

I always encourage niceness and empathy in open source, but I don't think it's necessary to always say thanks for an issue. I usually say thanks if someone finds a bug. I don't say thanks if you open an issue with a feature request. Then it's *you* wanting something from me. Yes, even if you intend to submit a PR. A pull request is only part of the work. Often reviewing a PR is much more work than writing the PR in the first place and I'm the one stuck maintaining the code for eternity.

**Comment by sindresorhus** [comment]
Regarding the feature request. I'm starting to think that having a single method `alphaSort` that accepts and options-object would have been better.

```js
['bar', 'baz', 'Baz'].sort(alphaSort({caseInsensitive: true, ignoreArticles: true}));
```

We need to discuss what to call such an option. Maybe we could call it `natural` and also sort numbers in a [natural order](https://blog.codinghorror.com/sorting-for-humans-natural-sort-order/)?

**Comment by papb** [comment]
@sindresorhus Great idea. Sorting numbers in a natural order is fantastic as well, very interesting. I like it. How about also auto-trimming and interpreting `\s+` as a single space?

Another question: for this new syntax, will `descending` be another option? Or maybe make two methods `alphaSort.ascending` and `alphaSort.descending`?

**Comment by sindresorhus** [comment]
> How about also auto-trimming and interpreting \s+ as a single space?

Yes

> Another question: for this new syntax, will descending be another option?

Option

**Comment by papb** [comment]
Cool, so I propose the following options:

* `descending` - boolean, default `false`
* `caseInsensitive` - boolean, default `false`
* `natural` - boolean, default `false`. When enabled:
  * The strings being compared are preprocessed as follows before the comparison:
    * Trim
    * `\s+(-\s+)*` is converted to a single space
  * Then, the comparison is performed with numbers being in natural order, i.e., all occurrences of `\d+` are treated as a single character, considering the numerical value
  * Ties are decided by sorting as if `natural` was false
* `ignoreArticles` - boolean, default `false`. Requires `natural` to be `true`. When enabled, the strings are further preprocessed (after `natural` preprocessing) as follows:
  * `^(the|a|an)([+-_. ]|$)` is removed (case insensitive, regardless of the `caseInsensitive` option)
  * Trim again to make sure we don't have a starting space after the above operation
  * Ties are decided by sorting as if `ignoreArticles` was false

Perhaps `ignoreArticles` could be `boolean | string[]`, and instead of `(the|a|an)` the provided strings are used, (and `true` becomes `['the', 'a', 'an']`).

**Comment by sindresorhus** [comment]
@papb That looks pretty good.

Does `ignoresArticles` really need to require `{natural: true}`? And maybe it should just be named `ignorePrefixes` and default to English articles? To be more generic.

**Comment by binyamin** [comment]
@sindresorhus @papb I appreciate your diligence to this issue. No waiting around, figuring out if this issue fits with the project's "vision". You took it, accepted it, understood it, and got to work. I wish there was more of this on GitHub.

**Comment by papb** [comment]
> Does `ignoresArticles` really need to require `{natural: true}`?

Hmm, maybe not, you're right. In this case I think the same whitespace operations I proposed for `natural` must be repeated in `ignoresArticles` too (i.e. trim and normalize `\s+` to a single space).

> And maybe it should just be named `ignorePrefixes` and default to English articles? To be more generic.

:+1:

**Comment by papb** [comment]
@b3u thank you :grin:

**Comment by sindresorhus** [comment]
> In this case I think the same whitespace operations I proposed for natural must be repeated in ignoresArticles too (i.e. trim and normalize \s+ to a single space).

👍🏻

**Comment by papb** [comment]
@b3u Are you still willing to do a PR for this?

**Comment by binyamin** [comment]
> Are you still willing to do a PR for this?

@papb sure.

> And maybe it should just be named ignorePrefixes and default to English articles? 

@sindresorhus How can the user override the default behavior? a _prefixes_ option?

**Comment by sindresorhus** [comment]
They set the `ignorePrefixes` option.

**Comment by binyamin** [comment]
> They set the `ignorePrefixes` option.

It defaults to English articles. How can the user change the default list of prefixes?

**Comment by papb** [comment]
@b3u Make the `ignorePrefixes` option able to receive `boolean | string[]`. If `false` is given, skip this. If `true` is given, use `['the', 'a', 'an']`. Otherwise, use the given array itself.

**Comment by binyamin** [comment]
> I don't say thanks if you open an issue with a feature request. Then it's _you_ wanting something from me...

(Just saw this https://github.com/sindresorhus/alpha-sort/issues/8#issuecomment-667664202) @sindresorhus Interesting outlook. I always thought of feature requests as if they point to something I may have missed. I see your points.

**Comment by binyamin** [comment]
@papb I don't seem to have time this month to create a fix for this issue. You can take it, if you want.

**Comment by papb** [comment]
Hi @binyamin, I opened a PR. Please take a look later :)
